# Generated by Django 6.0.5 on 2026-05-12 06:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(blank=True, max_length=100)),
                ('candidate_email', models.CharField(blank=True, max_length=200)),
                ('job_role', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('flagged', 'Flagged')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('attention_score', models.FloatField(default=100)),
                ('integrity_score', models.FloatField(default=100)),
                ('engagement_score', models.FloatField(default=100)),
                ('confidence_score', models.FloatField(default=100)),
                ('overall_score', models.FloatField(default=100)),
                ('tab_switch_count', models.IntegerField(default=0)),
                ('face_absent_count', models.IntegerField(default=0)),
                ('multi_face_count', models.IntegerField(default=0)),
                ('look_away_count', models.IntegerField(default=0)),
                ('audio_anomaly_count', models.IntegerField(default=0)),
                ('verdict', models.CharField(blank=True, max_length=50)),
                ('verdict_detail', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('face_absent', 'Face Absent'), ('multi_face', 'Multiple Faces'), ('gaze_away', 'Gaze Away'), ('audio_spike', 'Audio Spike'), ('background_motion', 'Background Motion'), ('looking_down', 'Looking Down'), ('head_turned', 'Head Turned'), ('system', 'System'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='interviews.session')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmotionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('happy', models.FloatField(default=0)),
                ('neutral', models.FloatField(default=0)),
                ('confused', models.FloatField(default=0)),
                ('focused', models.FloatField(default=0)),
                ('nervous', models.FloatField(default=0)),
                ('engaged', models.FloatField(default=0)),
                ('disengaged', models.FloatField(default=0)),
                ('suspicious', models.FloatField(default=0)),
                ('dominant', models.CharField(default='neutral', max_length=50)),
                ('gaze_direction', models.CharField(default='center', max_length=50)),
                ('looking_at_camera', models.BooleanField(default=True)),
                ('gaze_x', models.FloatField(default=0.5)),
                ('gaze_y', models.FloatField(default=0.5)),
                ('head_yaw', models.FloatField(default=0.5)),
                ('head_pitch', models.FloatField(default=0.45)),
                ('head_roll', models.FloatField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_snapshots', to='interviews.session')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
